	<div class="main base">
		<div class="clearfix">
			<section>
				<h2><?= $postManager->isOnePost() ? 'Article' : 'Blog' ?></h2>
				<?php if($postManager->havePosts()):?>
					<?= $postManager->getPagedLinks();?>
					<?php while ($postManager->havePosts() > 0): ?>
						<?php $post = $postManager->getNextPost();?>
						<article class="clearfix">
							<h3><?php if(!$postManager->isOnePost()): ?>
								<a href=<?= '"index.php?id='.$post['id'].'"'; ?>>
							<?php endif ?><?= $post['title']; ?>
							<?php if(!$postManager->isOnePost()): ?>
								</a>
							<?php endif ?></h3>
							<p>Posted by <?= $post['pseudo'];?> in: <?php /*$post['category'];*/ ?> on <?= $post['date']; ?></p>
							<div class="clearfix"><?= $post['content']; ?></div>
							<footer>
								<p class="tags">Tags : <?php /*the_tags('');*/ ?></p>
								<div>
									<?php if(!$postManager->isOnePost()): ?>
									<a href=<?= '"index.php?id='.$post['id'].'"'; ?>>Read More</a>
									<a href=<?= '"index.php?id='.$post['id'].'"'; ?>><?='0'?></a>
									<?php endif ?>
								</div>
							</footer>
						</article>
						<!--<?php/* comments_template(); */?>-->
					<?php endwhile ?>
					<?= $postManager->getPagedLinks();?>
				<?php else:?>
					<strong>Désole il n'y a pas d'article correspondant</strong>
				<?php endif;?>

			</section>

		</div>
	</div>